name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python: ["3.12", "3.13", "3.14"]
        postgres: ["15", "16", "17", "18"]

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: pg_dlock_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    env:
      PG_DLOCK_TEST_DSN: postgresql://postgres:postgres@localhost:5432/pg_dlock_test

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python }}
          enable-cache: true
          activate-environment: true

      - run: uv sync --locked --group dev

      - name: run tests
        run: coverage run -a -m pytest tests

      - uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test-pass:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: echo success
